cameras:
  common:
    width: 1280
    height: 720
    fps: 15.0
    pixel_format: mjpeg
  devices:
    front: /dev/v4l/by-id/cam_front
    rear: /dev/v4l/by-id/cam_rear
    left: /dev/v4l/by-id/cam_left
    right: /dev/v4l/by-id/cam_right
